### PR TITLE
Added Greek language support and fixes #442

### LINKED ISSUE #442: Bug when linking page with menu
# Bug

On menu edit, menu get a wrong link of page with double html. 
_e.x home.html.html_
# Reproduce error

Try edit a menu, then select a new page and then save it. You will notice that the linking page will be <page>.html.html instead of <page>.html

### PR DESCRIPTION
**Pull request by Rambou**
I've added Greek language file and translated all of the fields. I'm Greek so there shouldn't be any problem.... :wink:

### CODE REVIEW

**Comment by Rambou** [comment]
Also fixes #442

**Comment by madoublet** [comment]
Thanks again!  I am going to manually merge this into the beta3 branch rather than straight to master.  It should be released next week.

**Comment by Rambou** [comment]
Also added Background video plugin for material theme!!!

**Comment by Rambou** [comment]
selection_003

Example of background video

**Comment by joebordes** [comment]
I see GR translation is in R6 RC5 and I suppose the other changes have been handled by Matt, so I am closing the issue, just to clean up. Open new issues as needed.

Thanks

**Pull request closed without merging**
