### PR TITLE
Add Shepherd tour of page editor

### PR DESCRIPTION
**Pull request by axis80**
I've put quite a few clients and friends in front of the Respond backend thus far, and I've learned two things:

1) They have absolutely no idea where to begin with the editor when they see it for the first time.

2) Once I give them just five minutes of training on the basics, it "clicks" in their heads and they are able to start laying out pages.

This commit attempts to distill my standard five-minute training session into a Shepherd tour, similar to the one that is shown upon initial login.  My hope is that it will smooth the onboarding process for new users.

There is at least one imperfection.  Like the intro tour, it only displays during the first login.  We have no guarantee that someone will edit a page during their initial login session, so it's possible that some people will never see it.  It's unfortunately not possible to solve that without adding a "viewedEditorTour" column to the Users table.  That's beyond my capabilities and probably not worth tackling at this moment anyway, given that it's likely a somewhat rare case.   Despite that imperfection, I'm hoping you'll think this is a net gain for Respond's usability.

My starting point for this was the Respond 4 master branch, which is what I'm running in production.  Now I realize that I should have used the Respond 4.5 branch as a starting point.  Hopefully it will not be too difficult for you to merge this in (assuming you choose to)?

### CODE REVIEW

**Comment by joebordes** [comment]
:+1:

**Comment by madoublet** [comment]
Looks like there are some merge conflicts.  But, I will manually merge this.

**Comment by axis80** [comment]
I may have sent this pull request too soon.  It works fine with some themes, but not with others.  I am making some tweaks to the tour.js step definitions right now.  Once I am done I will either update this request (if I can figure out how) or create a new one.

**Comment by axis80** [comment]
OK, I just pushed some improvements.  I think I managed to clean it up drastically.  It now seems to work well with all themes, and at a variety of screen resolutions.  Please let me know if you have any comments or questions.

**Comment by madoublet** [comment]
This is fantastic.  I love the new tour.  I had to merge it manually, but it is now in the 4.5 branch.

**Pull request closed without merging**
